name: Auto Merge

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      name:
        description: 'Test deploy'
        required: true

concurrency: 
  group: 'auto-merge'
  cancel-in-progress: true

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        echo "Test 321" >> test.txt
        git add .
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git commit -m "Auto commit"
        git push origin main
