name: Auto Merge

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Test deploy'
        required: true

concurrency: 
  group: 'auto-merge'
  cancel-in-progress: true

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: echo "Test" >> test.txt && git add . && git commit -m "Auto commit" && git push origin main
